language: python

sudo: required

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install -r requirements.txt"
  - "pip install --upgrade pip"
  - "pip list"
  - "python setup.py develop"
  
script:
  - make test